# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    # item count per page
    items_per_page: '%env(int:ITEMS_PER_PAGE)%'
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    csrf_protection: ~

    #esi: true
    #fragments: true
#    form:
#        csrf_protection:
#            enabled: true
#            field_name: '_token' # Customize the hidden field name

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
