<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250825201143 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attachment (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    photo_link VARCHAR(255) NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(255) DEFAULT NULL,
                    photo_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    attachable_id INT DEFAULT NULL,
                    attachable_type VARCHAR(255) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE fertilizer (
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    use_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    plant_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX fertilizer__plant_id__ind ON fertilizer (plant_id)');

        $this->addSql('CREATE TABLE offspring (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    fruiting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    flowering_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    mass INT DEFAULT NULL,
                    color VARCHAR(64) DEFAULT NULL,
                    flavor VARCHAR(64) DEFAULT NULL,
                    quantity INT DEFAULT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    plant_id BIGINT DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX offspring__plant_id__ind ON offspring (plant_id)');
        $this->addSql('CREATE TABLE pest (
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    use_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    plant_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX pest__plant_id__ind ON pest (plant_id)');

        $this->addSql('CREATE TABLE plant (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    oid UUID DEFAULT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    qr_code_base64 VARCHAR(94) DEFAULT NULL,
                    room VARCHAR(64) NOT NULL,
                    purchase_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    vaccination_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    planting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    seller VARCHAR(255) DEFAULT NULL,
                    nursery VARCHAR(255) DEFAULT NULL,
                    price VARCHAR(10) DEFAULT NULL,
                    shipping_cost VARCHAR(10) DEFAULT NULL,
                    packaging_cost VARCHAR(10) DEFAULT NULL,
                    is_shown BOOLEAN DEFAULT true NOT NULL,
                    soil VARCHAR(255) DEFAULT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB030D72422A20A0 ON plant (oid)');
        $this->addSql('CREATE INDEX plant__oid__ind ON plant (oid)');
        $this->addSql('CREATE UNIQUE INDEX plant__oid__uniq ON plant (oid) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE status (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, letter VARCHAR(1) NOT NULL, description VARCHAR(1024) DEFAULT NULL, color VARCHAR(7) NOT NULL, color_description VARCHAR(1024) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B00651C8E02EE0A ON status (letter)');
        $this->addSql('CREATE TABLE stimulant (
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    use_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    plant_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX stimulant__plant_id__ind ON stimulant (plant_id)');
        $this->addSql('CREATE TABLE task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description VARCHAR(1024) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status_id BIGINT DEFAULT NULL, plant_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('ALTER TABLE fertilizer ADD CONSTRAINT FK_1525A45C1D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offspring ADD CONSTRAINT FK_41CD3FF21D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pest ADD CONSTRAINT FK_571DE95B1D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stimulant ADD CONSTRAINT FK_8B814791D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB256BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB251D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fertilizer DROP CONSTRAINT FK_1525A45C1D935652');
        $this->addSql('ALTER TABLE offspring DROP CONSTRAINT FK_41CD3FF21D935652');
        $this->addSql('ALTER TABLE pest DROP CONSTRAINT FK_571DE95B1D935652');
        $this->addSql('ALTER TABLE stimulant DROP CONSTRAINT FK_8B814791D935652');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB256BF700BD');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB251D935652');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE fertilizer');
        $this->addSql('DROP TABLE offspring');
        $this->addSql('DROP TABLE pest');
        $this->addSql('DROP TABLE plant');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE stimulant');
        $this->addSql('DROP TABLE task');
    }
}
