<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250825201143 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Make table for project entities';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attachment (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    is_shown BOOLEAN DEFAULT false NOT NULL,
                    filename VARCHAR(255) DEFAULT NULL,
                    path VARCHAR(255) DEFAULT NULL,
                    mime_type VARCHAR(50) DEFAULT NULL,
                    alt VARCHAR(255) NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    file_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    attachable_id INT DEFAULT NULL,
                    attachable_type VARCHAR(255) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE fertilizer (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    marker_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    letter VARCHAR(2) NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE offspring (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    plant_id BIGINT DEFAULT NULL,
                    fruiting_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    flowering_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    mass INT DEFAULT NULL,
                    color VARCHAR(64) DEFAULT NULL,
                    flavor VARCHAR(64) DEFAULT NULL,
                    quantity INT DEFAULT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE pest (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    marker_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    letter VARCHAR(2) NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE plant (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    oid UUID DEFAULT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    qr_code_link VARCHAR(255) DEFAULT NULL,
                    room VARCHAR(64) NOT NULL,
                    purchase_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    vaccination_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    planting_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    seller VARCHAR(255) DEFAULT NULL,
                    nursery VARCHAR(255) DEFAULT NULL,
                    price VARCHAR(10) DEFAULT NULL,
                    shipping_cost VARCHAR(10) DEFAULT NULL,
                    packaging_cost VARCHAR(10) DEFAULT NULL,
                    is_shown BOOLEAN DEFAULT true NOT NULL,
                    soil VARCHAR(1024) DEFAULT NULL,
                    is_sold BOOLEAN DEFAULT false NOT NULL,
                    selling_price VARCHAR(10) DEFAULT NULL,
                    selling_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE marker (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    letter VARCHAR(3) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    color VARCHAR(7) NOT NULL,
                    color_description VARCHAR(1024) DEFAULT NULL,
                    type VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE stimulant (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    marker_id BIGINT NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    manufacturer VARCHAR(255) DEFAULT NULL,
                    quantity INT NOT NULL,
                    letter VARCHAR(2) NOT NULL,
                    comment VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE watering (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    marker_id BIGINT NOT NULL,
                    watered_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    description TEXT DEFAULT NULL,
                    comment TEXT DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    amount INT NOT NULL,
                    type VARCHAR(255) NOT NULL,
                    method VARCHAR(255) NOT NULL,
                    temperature NUMERIC(3, 1) DEFAULT NULL,
                    PRIMARY KEY (id))');


        $this->addSql('CREATE TABLE usage (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    plant_id BIGINT DEFAULT NULL,
                    use_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    comment TEXT DEFAULT NULL,
                    usable_id BIGINT DEFAULT NULL,
                    usable_type VARCHAR(255) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE "group" (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    is_active BOOLEAN DEFAULT true NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1024) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE "user" (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    group_id BIGINT NOT NULL,
                    email VARCHAR(255) NOT NULL,
                    password VARCHAR(255) NOT NULL,
                    roles JSON NOT NULL,
                    refresh_token VARCHAR(32) DEFAULT NULL,
                    is_active BOOLEAN DEFAULT true NOT NULL,
                    last_name VARCHAR(64) NOT NULL,
                    first_name VARCHAR(64) NOT NULL,
                    middle_name VARCHAR(64) DEFAULT NULL,
                    phone VARCHAR(16) DEFAULT NULL,
                    avatar_link VARCHAR(255) DEFAULT NULL,
                    email_code VARCHAR(6) DEFAULT NULL,
                    email_confirmed BOOLEAN DEFAULT false NOT NULL,
                    phone_code VARCHAR(6) DEFAULT NULL,
                    phone_confirmed BOOLEAN DEFAULT false NOT NULL,
                    time_zone VARCHAR(20) DEFAULT \'Europe/Moscow\' NOT NULL,
                    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                    deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                    PRIMARY KEY (id))');

        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT attachment__group_id__fk  FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fertilizer ADD CONSTRAINT fertilizer__marker_id__fk FOREIGN KEY (marker_id) REFERENCES marker (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fertilizer ADD CONSTRAINT fertilizer__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant ADD CONSTRAINT plant__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT user__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offspring ADD CONSTRAINT offspring__plant_id__fk FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offspring ADD CONSTRAINT offspring__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pest ADD CONSTRAINT pest__marker_id__fk FOREIGN KEY (marker_id) REFERENCES marker (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pest ADD CONSTRAINT pest__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stimulant ADD CONSTRAINT stimulant__marker_id__fk FOREIGN KEY (marker_id) REFERENCES marker (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stimulant ADD CONSTRAINT stimulant__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE watering ADD CONSTRAINT watering__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE watering ADD CONSTRAINT watering__marker_id__fk FOREIGN KEY (marker_id) REFERENCES marker (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marker ADD CONSTRAINT marker__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE usage ADD CONSTRAINT usage__plant_id__fk FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE usage ADD CONSTRAINT usage__group_id__fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fertilizer DROP CONSTRAINT fertilizer__marker_id__fk');
        $this->addSql('ALTER TABLE fertilizer DROP CONSTRAINT fertilizer__group_id__fk');
        $this->addSql('ALTER TABLE plant DROP CONSTRAINT plant__group_id__fk');
        $this->addSql('ALTER TABLE user DROP CONSTRAINT user__group_id__fk');
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT attachment__group_id__fk');
        $this->addSql('ALTER TABLE offspring DROP CONSTRAINT offspring__plant_id__fk');
        $this->addSql('ALTER TABLE offspring DROP CONSTRAINT offspring__group_id__fk');
        $this->addSql('ALTER TABLE pest DROP CONSTRAINT pest__marker_id__fk');
        $this->addSql('ALTER TABLE pest DROP CONSTRAINT pest__group_id__fk');
        $this->addSql('ALTER TABLE stimulant DROP CONSTRAINT stimulant__marker_id__fk');
        $this->addSql('ALTER TABLE stimulant DROP CONSTRAINT stimulant__group_id__fk');
        $this->addSql('ALTER TABLE watering DROP CONSTRAINT watering__group_id__fk');
        $this->addSql('ALTER TABLE watering DROP CONSTRAINT watering__marker_id__fk');
        $this->addSql('ALTER TABLE marker DROP CONSTRAINT marker__group_id__fk');
        $this->addSql('ALTER TABLE usage DROP CONSTRAINT usage__plant_id__fk');
        $this->addSql('ALTER TABLE usage DROP CONSTRAINT usage__group_id__fk');

        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE fertilizer');
        $this->addSql('DROP TABLE offspring');
        $this->addSql('DROP TABLE pest');
        $this->addSql('DROP TABLE plant');
        $this->addSql('DROP TABLE marker');
        $this->addSql('DROP TABLE stimulant');
        $this->addSql('DROP TABLE watering');
        $this->addSql('DROP TABLE usage');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE "user"');
    }
}
