api_v1:
    resource: ../src/Controller/Api/
    type: attribute

app_web:
    resource:
        path: ../src/Controller/Web/
        namespace: App\Controller\Web
        exclude: '../src/Controller/Api/'

    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: '%locale%'
