###
POST {{protocol}}{{base_url}}/api/{{api_version}}/get-token
Accept: application/json
Content-Type: application/json

{
    "email": "mail@mail.ru",
    "password": "12345678"
}

###
POST {{protocol}}{{base_url}}/api/{{api_version}}/refresh-token
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
POST {{protocol}}//{{base_url}}/api/{{api_version}}/get-token
Authorization: Basic mail@mail.ru 12345678
